services:
  backend:
    container_name: elitecard-backend
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=4000
